import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tope & Oyin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        
        <main className="flex-1">
          {children}
        </main>

        <footer className="border-t border-zinc-200 bg-white py-4 text-center text-sm text-zinc-600">
          <span className="font-medium text-primary">Powered by Aeritzon</span> © 2026
        </footer>

      </body>
    </html>
  );
}
